version: '3.9'

services:
  web-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL:-postgres://app:app@localhost:5432/db}
        ARCHIVE_ROOT: /archive
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://app:app@localhost:5432/db}
      ARCHIVE_ROOT: /archive
    volumes:
      - "/mnt/webarchive/new-archive2:/archive"
    network_mode: host
