version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - nyculib-web-archive_archive-db:/var/lib/postgresql/data/pgdata
    networks:
      - webarchive-network

networks:
  webarchive-network:
    external: true

volumes:
  nyculib-web-archive_archive-db:
    external: true
