import { Card } from "@/components/card";
import { getRecords } from "@/services/record";
import { type ApiRecord } from "@/types/record";
import { type GetStaticProps, type NextPage } from "next";
import Head from "next/head";

type RecordPageProps = {
  records: ApiRecord[];
};

const Home: NextPage<RecordPageProps> = ({ records }) => {
  console.log(records);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 md:grid-cols-2">
        {records.map((record) => (
          <Card key={record.id} {...record}></Card>
        ))}
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<RecordPageProps> = async () => {
  const records = await getRecords();

  return {
    props: {
      records,
    },
    revalidate: 3600,
  };
};

export default Home;
