import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web Archive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-12 font-serif">
        <h1 className="text-5xl font-black">國立陽明交通大學網站典藏庫</h1>
        <h1 className="mb-10 py-3 px-4 text-xl">
          National Yang Ming Chiao Tung University Web Archiving System
        </h1>
        <div className="flex max-w-full gap-3"></div>
      </main>
    </>
  );
};

export default Home;
