import { Card } from "@/components/card";
import { Collapse } from "@/components/collapse";
import { ScrollBar } from "@/components/scroll";
import { getRecords } from "@/services/record";
import { type ApiRecord } from "@/types/record";
import { type GetStaticProps, type NextPage } from "next";
import Head from "next/head";

type RecordPageProps = {
  records: ApiRecord[];
};

const Home: NextPage<RecordPageProps> = ({ records }) => {
  console.log(records);
  return (
    <>
      <Head>
        <title>Web Archive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-12 font-serif">
        <h1 className="text-5xl font-black">國立陽明交通大學網站典藏庫</h1>
        <h1 className="mb-10 py-3 px-4 text-xl">
          National Yang Ming Chiao Tung University Web Archiving System
        </h1>
        <div className="flex max-w-full gap-3">
          <Collapse />
          <div className="min-w-0 flex-1">
            <ScrollBar />
            <section className="mt-6 grid grid-cols-1 gap-x-12 px-16 lg:grid-cols-2">
              {records.map((record) => (
                <Card key={record.id} {...record}></Card>
              ))}
            </section>
          </div>
          <div className="px-10">
            <Collapse />
          </div>
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<RecordPageProps> = async () => {
  const records = await getRecords();

  return {
    props: {
      records,
    },
    revalidate: 3600,
  };
};

export default Home;
