import Head from "next/head";
import type { PropsWithChildren } from "react";
import React from "react";

export const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Web Archive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto h-screen pt-10 font-serif">
        {children}
      </main>
    </>
  );
};
